# Generated by Django 3.0.8 on 2020-07-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('idade', models.IntegerField(null=True)),
                ('temperatura_maxima', models.FloatField(null=True)),
                ('data_inicio_sintomas', models.DateField(null=True)),
            ],
        ),
    ]
